version: "3.9"

networks:
  traefik-public:
    external: true

volumes:
  yamdb_static:
  yamdb_media:
  yamdb_logs:
  yamdb_db:

services:
  db:
    image: postgres:13.0-alpine
    container_name: yamdb_db
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - yamdb_db:/var/lib/postgresql/data
    networks:
      - traefik-public

  backend:
    build:
      context: ../api_yamdb
      dockerfile: Dockerfile
    image: yamdb_backend:latest
    container_name: yamdb_backend
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - yamdb_static:/app/static
      - yamdb_media:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate --noinput &&
             gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    networks:
      - traefik-public

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: yamdb_frontend:latest
    container_name: yamdb_frontend
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - yamdb_static:/usr/share/nginx/html/static
      - yamdb_media:/usr/share/nginx/html/media
      - yamdb_logs:/var/log/nginx
    expose:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.yamdb.rule=Host(`bardev.ru`) && PathPrefix(`/yamdb`)
      - traefik.http.routers.yamdb.entrypoints=websecure
      - traefik.http.routers.yamdb.tls.certresolver=le
      # Чтобы главная страница (портфолио) имела больший приоритет
      - traefik.http.routers.yamdb.priority=10
      # Объявляем путь как "yamdb"
      - traefik.http.middlewares.yamdb-stripprefix.stripprefix.prefixes=/yamdb
      - traefik.http.routers.yamdb.middlewares=yamdb-stripprefix
    networks:
      - traefik-public
