version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build:
      context: ../api_yamdb       # собираем образ из папки с Django-проектом
      dockerfile: Dockerfile     # в ней должен быть Dockerfile веб-приложения
    image: yamdb_web:latest
    ports:
      - "8000:8000"
    container_name: yamdb_web
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate --noinput &&
             gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"

  nginx:                                      # теперь это фронтенд + reverse-proxy
    build:
      context: ../frontend                    # здесь лежит Dockerfile React-приложения
      dockerfile: Dockerfile
    container_name: yamdb_frontend
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_value:/app/static/            # чтобы раздавать /static/**
      - media_value:/app/media/              # чтобы раздавать /media/**
      - logs_value:/var/log/nginx/           # пишем логи внутрь тома

volumes:
  static_value:
  media_value:
  logs_value:
  data_value: